name: Google Sheet Automation

on:
  schedule:
    - cron: '01 17 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call Apps Script
        run: |
          curl "https://script.google.com/macros/s/AKfycbwxyNGyklZkL23z1iS3_A0ViAAT8DjGl_d-wCVJpiwSo5q2cylluZUh8w8dcDlMs2b5/exec"
