name: Google Sheet Automation

on:
  schedule:
    - cron: '40 18 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call Apps Script
        run: |
          curl "https://script.google.com/macros/s/AKfycbyQ-6RCT_UtdKTh_0M_5YbmhWEJ4rZd1ErTFp1pg9ZPZZCx4d4QRgxHBj29ktszHuln/exec"
