name: Google Sheet Automation

on:
  schedule:
    - cron: '01 17 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call Apps Script
        run: |
          curl "https://script.google.com/macros/s/AKfycbzPM2O40Yy6ZM6dPst4PGfzuSTK_HWfg4OIryZVBP_3_DH8vSJq1u2HUEOSNgVpSkA/exec"
